# Generated by Django 2.2.2 on 2019-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Employee Name')),
                ('salary', models.IntegerField(null=True, verbose_name='Salary')),
                ('job', models.CharField(choices=[('PM', 'Project Manager'), ('SE', 'Software Engineer'), ('DA', 'Data Analyst')], max_length=30, verbose_name='Post')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
