# Generated by Django 2.2.2 on 2019-07-02 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='book',
            field=models.CharField(choices=[('Mat', 'Mathematics'), ('Sci', 'Science'), (
                'Hin', 'Hindi')], default='', max_length=30, verbose_name='Books_issued'),
            preserve_default=False,
        ),
    ]
