# Generated by Django 2.2.2 on 2019-07-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190702_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.CharField(max_length=30, verbose_name='TeacherName'),
        ),
    ]
