# Generated by Django 2.2.2 on 2019-07-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190702_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pic',
        ),
    ]
